version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR and Docker Hub 
      # - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Builing image from docker file.
      - docker build -t dgl-citation-network:custom-torch-1.8 -f Dockerfile .
      - echo Pushing image to Amazon ECR.
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 939595455984.dkr.ecr.eu-west-1.amazonaws.com
      - docker tag dgl-citation-network:custom-torch-1.8 939595455984.dkr.ecr.eu-west-1.amazonaws.com/dgl-citation-network:custom-torch-1.8
      - docker push 939595455984.dkr.ecr.eu-west-1.amazonaws.com/dgl-citation-network:custom-torch-1.8
  post_build:
    commands:
      - echo Build completed on `date`